### PR TITLE
Update archiver to v1.3.0. Fix for empty tgz files

### PR DESCRIPTION
**Pull request by jacek-pulit**

### CODE REVIEW

**Comment by XhmikosR** [comment]
@jacek-pulit: are there any API changes?

**Comment by jacek-pulit** [comment]
@XhmikosR as you can see here: https://github.com/archiverjs/node-archiver/blob/master/CHANGELOG.md - some deps upgrades, minor doc fixes, etc. But old version creates empty archive files in tgz mode on node > 6.9.x

**Comment by jacek-pulit** [comment]
@XhmikosR Will you publish it shortly to the npm?

**Comment by XhmikosR** [comment]
Done, https://github.com/gruntjs/grunt-contrib-compress/releases/tag/v1.4.2

**Pull request merged**
