### PR TITLE
update iltorb to 2.4.3

### LINKED ISSUE #214: Update iltorb to fix tar vulnerability and compatibility with Node 12
Whenever you have time, the latest [iltorb 2.4.3](https://github.com/MayhemYDG/iltorb/blob/master/CHANGELOG.md#243---2019-04-24) fixes `tar` version  dependency and brings Node 12 support.

### PR DESCRIPTION
**Pull request by caseyjhol**
fixes tar vulnerability
closes #214 and closes #215

### CODE REVIEW

**Comment by vladikoff** [comment]
seems like there is a problem with node 4 , we need to move out of node 4 to merge this it seems

**Comment by caseyjhol** [comment]
Yes it looks like Node 4 support was dropped in iltorb v2.3.1.

**Comment by y-a-v-a** [comment]
According to this figure from NodeJS, you could consider dropping support for v4 anyway, since it is hardly being downloaded anymore.

nodejs version download

**Comment by dwbruhn** [comment]
Any update on this?

**Comment by dickeylth** [comment]
Any update on this? 😀

**Comment by dickeylth** [comment]
```
[1/5] scripts.install @ali/clam-plugin-basement@1.6.17 › grunt-contrib-compress@1.5.0 › iltorb@^1.3.10 run "detect-libc prebuild-install || node-gyp rebuild", root: "/Users/dickeylth/.clam/@ali/clam-toolkit-xpi/package/node_modules/_iltorb@1.3.10@iltorb"
prebuild-install http request GET https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v64-darwin-x64.tar.gz
prebuild-install http 404 https://github.com/MayhemYDG/iltorb/releases/download/v1.3.10/iltorb-v1.3.10-node-v64-darwin-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=10.16.3 runtime=node arch=x64 platform=darwin)
  CC(target) Release/obj.target/iltorb/brotli/common/dictionary.o
  CC(target) Release/obj.target/iltorb/brotli/dec/bit_reader.o
  CC(target) Release/obj.target/iltorb/brotli/dec/decode.o
  CC(target) Release/obj.target/iltorb/brotli/dec/huffman.o
  CC(target) Release/obj.target/iltorb/brotli/dec/state.o
  CC(target) Release/obj.target/iltorb/brotli/enc/backward_references.o
  CC(target) Release/obj.target/iltorb/brotli/enc/backward_references_hq.o
  CC(target) Release/obj.target/iltorb/brotli/enc/bit_cost.o
  CC(target) Release/obj.target/iltorb/brotli/enc/block_splitter.o
  CC(target) Release/obj.target/iltorb/brotli/enc/brotli_bit_stream.o
  CC(target) Release/obj.target/iltorb/brotli/enc/cluster.o
  CC(target) Release/obj.target/iltorb/brotli/enc/compress_fragment.o
  CC(target) Release/obj.target/iltorb/brotli/enc/compress_fragment_two_pass.o
  CC(target) Release/obj.target/iltorb/brotli/enc/dictionary_hash.o
  CC(target) Release/obj.target/iltorb/brotli/enc/encode.o
  CC(target) Release/obj.target/iltorb/brotli/enc/entropy_encode.o
  CC(target) Release/obj.target/iltorb/brotli/enc/histogram.o
  CC(target) Release/obj.target/iltorb/brotli/enc/literal_cost.o
  CC(target) Release/obj.target/iltorb/brotli/enc/memory.o
  CC(target) Release/obj.target/iltorb/brotli/enc/metablock.o
  CC(target) Release/obj.target/iltorb/brotli/enc/static_dict.o
  CC(target) Release/obj.target/iltorb/brotli/enc/utf8_util.o
  CXX(target) Release/obj.target/iltorb/src/common/allocator.o
  CXX(target) Release/obj.target/iltorb/src/common/stream_coder.o
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode.o
../src/dec/stream_decode.cc:14:72: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
                                                                       ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/dec/stream_decode.cc:40:49: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  StreamDecode* obj = new StreamDecode(info[0]->ToObject());
                                                ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/dec/stream_decode.cc:48:35: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  Local<Object> buffer = info[0]->ToObject();
                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
3 warnings generated.
  CXX(target) Release/obj.target/iltorb/src/dec/stream_decode_worker.o
../src/dec/stream_decode_worker.cc:46:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../_nan@2.14.0@nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../_nan@2.14.0@nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/dec/stream_decode_worker.cc:52:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../_nan@2.14.0@nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../_nan@2.14.0@nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode.o
../src/enc/stream_encode.cc:14:51: warning: 'Int32Value' is deprecated [-Wdeprecated-declarations]
    val = Nan::Get(params, key).ToLocalChecked()->Int32Value();
                                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2478:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:20:51: warning: 'Int32Value' is deprecated [-Wdeprecated-declarations]
    val = Nan::Get(params, key).ToLocalChecked()->Int32Value();
                                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2478:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:26:51: warning: 'Int32Value' is deprecated [-Wdeprecated-declarations]
    val = Nan::Get(params, key).ToLocalChecked()->Int32Value();
                                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2478:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:32:51: warning: 'Int32Value' is deprecated [-Wdeprecated-declarations]
    val = Nan::Get(params, key).ToLocalChecked()->Int32Value();
                                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2478:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:44:51: warning: 'Int32Value' is deprecated [-Wdeprecated-declarations]
    val = Nan::Get(params, key).ToLocalChecked()->Int32Value();
                                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2478:3: note: 'Int32Value' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", int32_t Int32Value() const);
  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:50:72: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
    Local<Object> dictionary = Nan::Get(params, key).ToLocalChecked()->ToObject();
                                                                       ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:76:49: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  StreamEncode* obj = new StreamEncode(info[0]->ToObject());
                                                ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
../src/enc/stream_encode.cc:84:35: warning: 'ToObject' is deprecated [-Wdeprecated-declarations]
  Local<Object> buffer = info[0]->ToObject();
                                  ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8.h:2455:10: note: 'ToObject' has been explicitly marked deprecated here
  inline V8_DEPRECATED("Use maybe version", Local<Object> ToObject() const);
         ^
/Users/dickeylth/.node-gyp/10.16.3/include/node/v8config.h:327:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated))
                            ^
8 warnings generated.
  CXX(target) Release/obj.target/iltorb/src/enc/stream_encode_worker.o
../src/enc/stream_encode_worker.cc:47:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(1, argv);
              ^
../../_nan@2.14.0@nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../_nan@2.14.0@nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
../src/enc/stream_encode_worker.cc:53:15: warning: 'Call' is deprecated [-Wdeprecated-declarations]
    callback->Call(2, argv);
              ^
../../_nan@2.14.0@nan/nan.h:1739:3: note: 'Call' has been explicitly marked deprecated here
  NAN_DEPRECATED inline v8::Local<v8::Value>
  ^
../../_nan@2.14.0@nan/nan.h:104:40: note: expanded from macro 'NAN_DEPRECATED'
# define NAN_DEPRECATED __attribute__((deprecated))
                                       ^
2 warnings generated.
  CXX(target) Release/obj.target/iltorb/src/iltorb.o
  SOLINK_MODULE(target) Release/iltorb.node
  COPY ../build/bindings/iltorb.node
  TOUCH Release/obj.target/action_after_build.stamp
[1/5] scripts.install @ali/clam-plugin-basement@1.6.17 › grunt-contrib-compress@1.5.0 › iltorb@^1.3.10 finished in 28s
```

It's really very annoying install experience. Hope this pr could be merged soon.

**Pull request merged**
